## Regression Problem with ANN

**EstimatedSalary as target variable**

In [159]:
import pickle
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [160]:
df = pd.read_csv('data/customer_churn_data.csv')
df.head()

# EstimatedSalary as target variable

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [161]:
# Drop unnecessary columns
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

In [162]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Encoding Geography

In [163]:
geography_ohe = OneHotEncoder(drop='first', sparse_output=False)
geography_ohe_data = geography_ohe.fit_transform(df[['Geography']])
geography_ohe_data

array([[0., 0.],
       [0., 1.],
       [0., 0.],
       ...,
       [0., 0.],
       [1., 0.],
       [0., 0.]], shape=(10000, 2))

In [164]:
geography_ohe.get_feature_names_out()

array(['Geography_Germany', 'Geography_Spain'], dtype=object)

In [165]:
geography_ohe_df = pd.DataFrame(geography_ohe_data, columns=geography_ohe.get_feature_names_out())
geography_ohe_df.head()

   Geography_Germany  Geography_Spain
0                0.0              0.0
1                0.0              1.0
2                0.0              0.0
3                0.0              0.0
4                0.0              1.0

### Encoding Gender

In [166]:
gender_ohe = OneHotEncoder(drop='first', sparse_output=False)
gender_ohe_data = gender_ohe.fit_transform(df[['Gender']])
gender_ohe_data

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]], shape=(10000, 1))

In [167]:
gender_ohe_df = pd.DataFrame(gender_ohe_data, columns=gender_ohe.get_feature_names_out())
gender_ohe_df.head()

   Gender_Male
0          0.0
1          0.0
2          0.0
3          0.0
4          0.0

#### Updating original dataframe with encoded columns

In [168]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [169]:
df.drop(columns=['Geography', 'Gender'], inplace=True)
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1
3,699,39,1,0.00,2,0,0,93826.63,0
4,850,43,2,125510.82,1,1,1,79084.10,0

In [170]:
df = pd.concat([df, gender_ohe_df, geography_ohe_df], axis=1)
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Male,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1,0.0,0.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,42,8,159660.80,3,1,0,113931.57,1,0.0,0.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,0,0.0,0.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

### Splitting data for train and test

In [171]:
X = df.drop('EstimatedSalary', axis=1)
y = df['EstimatedSalary']

In [172]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Standardizing the data

In [173]:
# fit transform on train
# transform on test

# Both are for X

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Regression ANN

In [174]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [175]:
X_train.shape[1]

11

In [176]:
X_train_scaled[0].shape

(11,)

In [177]:
model = Sequential([
    Dense(64, activation='relu', input_shape=X_train_scaled[0].shape),
    Dense(32, activation='relu'),
    Dense(1) # Output layer for regression
])

# Compile Model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

/workspaces/ANN-Customer-Churn/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_24 (Dense)                │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,881 (11.25 KB)

 Trainable params: 2,881 (11.25 KB)

 Non-trainable params: 0 (0.00 B)

In [178]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime('%Y%M%D-%H%M%S')
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [179]:
# Set Up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [180]:
# Train model
history = model.fit(
    X_train_scaled, y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100395.6562 - mae: 100395.6562 - val_loss: 98584.0703 - val_mae: 98584.0703
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99874.0859 - mae: 99874.0859 - val_loss: 97521.5547 - val_mae: 97521.5547
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 98013.3047 - mae: 98013.3047 - val_loss: 94772.1562 - val_mae: 94772.1562
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 94263.7500 - mae: 94263.7500 - val_loss: 90028.7656 - val_mae: 90028.7656
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 88586.5469 - mae: 88586.5469 - val_loss: 83554.6719 - val_mae: 83554.6719
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 81392.3047 - mae: 81392.3047 - val_loss: 76031.7031 - val_mae: 76031.7031
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 73570.5234 - mae: 73570.5234 - val_loss: 68565.5312 - val_mae: 68565.5312
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 66212.7734 - mae: 66212.7734 - val_loss: 61930.9414 - val_mae: 61930.9414
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 60115.3594 - mae: 60115.3594 - val_loss: 56937.0039 - val_mae: 56937.0039
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55801.2734 - mae: 55801.2734 - val_loss: 53716.5703 - val_mae: 53716.5703
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53128.5000 - mae: 53128.5000 - val_loss: 51865.8555 - val_mae: 51865.8555
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51671.6133 - mae: 51671.6133 - val_loss: 51052.7539 - val_mae: 51052.7539
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50958.6367 - mae: 50958.6367 - val_loss: 50728.8594 - val_mae: 50728.8594
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50626.1328 - mae: 50626.1328 - val_loss: 50634.8594 - val_mae: 50634.8594
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50462.0195 - mae: 50462.0195 - val_loss: 50613.8438 - val_mae: 50613.8438
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50361.5156 - mae: 50361.5156 - val_loss: 50594.8867 - val_mae: 50594.8867
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50288.0898 - mae: 50288.0898 - val_loss: 50568.1367 - val_mae: 50568.1367
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50230.9297 - mae: 50230.9297 - val_loss: 50554.9922 - val_mae: 50554.9922
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50184.3945 - mae: 50184.3945 - val_loss: 50536.4609 - val_mae: 50536.4609
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50144.1758 - mae: 50144.1758 - val_loss: 50520.9727 - val_mae: 50520.9727
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50107.1016 - mae: 50107.1016 - val_loss: 50502.2344 - val_mae: 50502.2344
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50076.1719 - mae: 50076.1719 - val_loss: 50489.0117 - val_mae: 50489.0117
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50046.0781 - mae: 50046.0781 - val_loss: 50475.3984 - val_mae: 50475.3984
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50017.1133 - mae: 50017.1133 - val_loss: 50461.2461 - val_mae: 50461.2461
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49989.2422 - mae: 49989.2422 - val_loss: 50444.6406 - val_mae: 50444.6406
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49962.4922 - mae: 49962.4922 - val_loss: 50437.8164 - val_mae: 50437.8164
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49942.7305 - mae: 49942.7305 - val_loss: 50417.7695 - val_mae: 50417.7695
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49917.2891 - mae: 49917.2891 - val_loss: 50414.1016 - val_mae: 50414.1016
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49898.5039 - mae: 49898.5039 - val_loss: 50403.3242 - val_mae: 50403.3242
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49878.0000 - mae: 49878.0000 - val_loss: 50394.0703 - val_mae: 50394.0703
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49859.5352 - mae: 49859.5352 - val_loss: 50390.4258 - val_mae: 50390.4258
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49839.7148 - mae: 49839.7148 - val_loss: 50382.3867 - val_mae: 50382.3867
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49822.0898 - mae: 49822.0898 - val_loss: 50374.3672 - val_mae: 50374.3672
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49806.8477 - mae: 49806.8477 - val_loss: 50369.2344 - val_mae: 50369.2344
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49792.2266 - mae: 49792.2266 - val_loss: 50361.5508 - val_mae: 50361.5508
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49774.3711 - mae: 49774.3711 - val_loss: 50363.5625 - val_mae: 50363.5625
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49764.9219 - mae: 49764.9219 - val_loss: 50358.1016 - val_mae: 50358.1016
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49747.8594 - mae: 49747.8594 - val_loss: 50353.4648 - val_mae: 50353.4648
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49733.9844 - mae: 49733.9844 - val_loss: 50347.8477 - val_mae: 50347.8477
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49721.9023 - mae: 49721.9023 - val_loss: 50343.3086 - val_mae: 50343.3086
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49709.1992 - mae: 49709.1992 - val_loss: 50338.7734 - val_mae: 50338.7734
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49698.1406 - mae: 49698.1406 - val_loss: 50342.3984 - val_mae: 50342.3984
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49687.5469 - mae: 49687.5469 - val_loss: 50341.8477 - val_mae: 50341.8477
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49674.3984 - mae: 49674.3984 - val_loss: 50338.9453 - val_mae: 50338.9453
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49667.9062 - mae: 49667.9062 - val_loss: 50337.1523 - val_mae: 50337.1523
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49657.4609 - mae: 49657.4609 - val_loss: 50343.7695 - val_mae: 50343.7695
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49646.2188 - mae: 49646.2188 - val_loss: 50341.5664 - val_mae: 50341.5664
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49637.7461 - mae: 49637.7461 - val_loss: 50332.8750 - val_mae: 50332.8750
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49627.8438 - mae: 49627.8438 - val_loss: 50327.0391 - val_mae: 50327.0391
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49620.0430 - mae: 49620.0430 - val_loss: 50326.3984 - val_mae: 50326.3984
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49610.7031 - mae: 49610.7031 - val_loss: 50333.9766 - val_mae: 50333.9766
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49604.0781 - mae: 49604.0781 - val_loss: 50332.7305 - val_mae: 50332.7305
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49595.1914 - mae: 49595.1914 - val_loss: 50340.5703 - val_mae: 50340.5703
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49590.2422 - mae: 49590.2422 - val_loss: 50331.5625 - val_mae: 50331.5625
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49580.2422 - mae: 49580.2422 - val_loss: 50341.0273 - val_mae: 50341.0273
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49571.4062 - mae: 49571.4062 - val_loss: 50339.2812 - val_mae: 50339.2812
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49565.6016 - mae: 49565.6016 - val_loss: 50344.1758 - val_mae: 50344.1758
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49558.1953 - mae: 49558.1953 - val_loss: 50335.8555 - val_mae: 50335.8555
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49552.5586 - mae: 49552.5586 - val_loss: 50335.7031 - val_mae: 50335.7031
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49545.7734 - mae: 49545.7734 - val_loss: 50332.3867 - val_mae: 50332.3867

In [181]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [182]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 28346), started 0:07:12 ago. (Use '!kill 28346' to kill it.)

In [183]:
test_loss, test_mae = model.evaluate(X_test_scaled, y_test)
print(f"Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50326.3984 - mae: 50326.3984
Test MAE: 50326.3984375

In [184]:
model.save('model_artifacts/regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.